ALTER TABLE student
ADD COLUMN CONSTRAINT age_constraint CHECK (age > 16),
ALTER COLUMN name SET NOT NULL,
ADD CONSTRAINT name_unique UNIQUE (name),
ALTER COLUMN age SET DEFAULT 20;


ALTER TABLE faculty
ADD CONSTRAINT color_unique UNIQUE (color);